-- ✅ 현재 워커 코드 및 Supabase 구조에 맞춘 schema

create table if not exists public.btc_chart_data (
  id         bigint generated by default as identity primary key,
  "timestamp" bigint not null,                   -- epoch seconds
  open       double precision not null,
  high       double precision not null,
  low        double precision not null,
  close      double precision not null,
  created_at timestamptz not null default now()
);

-- 유니크 제약 조건: 타임스탬프 중복 방지
create unique index if not exists uq_btc_chart_data_ts
  on public.btc_chart_data("timestamp");

-- 정렬용 인덱스
create index if not exists idx_btc_chart_data_ts_desc
  on public.btc_chart_data("timestamp" desc);

-- RLS 및 공개 읽기 허용
alter table public.btc_chart_data enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='btc_chart_data' and policyname='read_all'
  ) then
    create policy read_all on public.btc_chart_data
      for select using (true);
  end if;
end $$;
